config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }
  root 'home#index'

  scope defaults: { format: :html} do
    resources :products do
      member do
        put :subscribe
        delete :unsubscribe
      end
    end

    resources :home, only: [] do
      collection do
        get 'index/(:tag)', action: :index, as: :all
        get 'mine/(:tag)', action: :mine, as: :mine
      end
    end
  end

  scope defaults: { format: :json } do
    namespace :api do
      resources :products, only: %i[index show]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_tags, dependent: :destroy
  has_many :tags, through: :product_tags
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, :source => :user

  validates :title, presence: true
  validates :website_url, presence: true, url: true

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  default_scope { includes(:subscribers, :tags) }
  scope :contains_search, -> (search) { search ? where("products.title like ? OR products.description like ?", "%#{search}%", "%#{search}%") : all }
  scope :by_user, -> (user) { where(users: { id: user.id }) }
  scope :by_tag, -> (tag) { where(tags: { description: tag }) }

  ATTRIBUTES_FOR_JSON = %i[
    id
    title
    description
    website_url
    created_at
    updated_at
  ].freeze

  METHODS_FOR_JSON = %i[
    picture_url
    subscriber_count
    tag_list
  ].freeze

  def as_json(options = {})
    options[:only] ||= ATTRIBUTES_FOR_JSON
    options[:methods] ||= METHODS_FOR_JSON
    super options
  end

  def tag_list
    self.tags.all.map(&:description).join(', ')
  end

  def tag_list=(tag_list)
    self.tags = tag_list.split(',').map do |n|
      Tag.find_or_create_by(description: n.strip)
    end
  end

  def picture_url
    picture.url
  end

  def subscriber_count
    subscribers.count
  end

  def subscribe(user)
    self.subscribers << user
  end

  def unsubscribe(user)
    self.subscribers.delete(user)
  end
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :product_tags, dependent: :destroy
  has_many :products, through: :product_tags

  validates :description, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  NO_SPECIAL_CHARS = /\A[^{}\[\]()<>;:!@#$%^&*\\]+\z/

  has_many :subscriptions, dependent: :destroy
  has_many :product_subscriptions, through: :subscriptions, :source => :product

  devise :database_authenticatable, :registerable, :trackable, :validatable

  validates :first_name, presence: true, allow_blank: false, format: { with: NO_SPECIAL_CHARS, message: 'does not allow certain special characters' }
  validates :last_name, presence: true, allow_blank: false, format: { with: NO_SPECIAL_CHARS, message: 'does not allow certain special characters' }
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
  before_action :set_product, only: [:show]
  respond_to :json

  # GET /products
  def index
    @products = Product.all
    render json: @products
  end

  # GET /products/1
  def show
    if @product
      render json: @product
    else
      head :not_found
    end
  end

  private
    def set_product
      begin
        @product = Product.find(params[:id])
      rescue
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :current_user

  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html

  def index
    unless params[:tag]
      @products = Product.contains_search(home_params[:search])
    else
      @products = Product.contains_search(home_params[:search]).by_tag(home_params[:tag])
    end
    @tags = Tag.all
  end

  def mine
    unless params[:tag]
      @products = Product.by_user(current_user).contains_search(home_params[:search])
    else
      @products = Product.by_user(current_user).contains_search(home_params[:search]).by_tag(home_params[:tag])
    end
    @tags = Tag.all
  end

  protected

  def home_params
    params.permit(:tag, :search)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :subscribe, :unsubscribe]
  before_action :authenticate_user!, only: [:subscribe, :unsubscribe]
  respond_to :html

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    if @product.destroy
      redirect_to products_url, notice: 'Product was successfully destroyed.'
    end
  end


  # PUT /products/1/subscribe
  def subscribe
    if @product.subscribe(current_user)
      redirect_back fallback_location: root_path, notice: "You have subscribed to #{@product.title}"
    end
  end

  # DELETE /products/1/unsubscribe
  def unsubscribe
    if @product.unsubscribe(current_user)
      redirect_back fallback_location: root_path, notice: "You have unsubscribed from #{@product.title}"
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :website_url, :picture, :tag_list)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  ## Todo: default devise respond_with/responder doesn't seem to be playing nice with turbolinks/rails5
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        redirect_to after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        redirect_to after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  ## Todo: default devise respond_with/responder doesn't seem to be playing nice with turbolinks/rails5
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to after_sign_in_path_for(resource)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="row">
  <div id="tag_feed" class="col">
    <h2>Tags</h2>
    <%= render 'tags/index', tags: @tags %>
  </div>

  <div id="item_feed" class="col">
    <h2>Products</h2>
    <% if @products.empty? %>
      <span>No products, navigate to <%= link_to 'products page', products_path() %> to add some.</span>
    <% end %>
    <%= render 'products/index', products: @products %>
  </div>
</div>

app/views/home/mine.html.erb
<div class="row">
  <div id="tag_feed" class="col">
    <h2>Tags</h2>
    <%= render 'tags/index', tags: @tags %>
  </div>

  <div id="item_feed" class="col">
    <h2>My Product Subscriptions</h2>
    <% if @products.empty? %>
      <span>No subscriptions.</span>
    <% end %>
    <%= render 'products/index', products: @products %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hamhunt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div id="content">
      <p id="notice"><%= notice %></p>
      <p id="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product, local: true, html: { multipart: true } do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :website_url %>
    <%= form.text_field :website_url, id: :product_website_url %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <% if @product.picture.exists? %>
      <img src="<%= product.picture.url(:thumb) %>"/>
      <br/>
    <% end %>
    <%= form.file_field :picture, id: :picture %>
  </div>

  <div class="field">
    <%= form.label :tag_list %>
    <%= form.text_field :tag_list, id: :tag_list, placeholder: "Comma seperated list of tags..." %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_index.html.erb
<% products.each do |product| %>
  <%= render 'products/item', product: product %>
<% end %>

app/views/products/_item.html.erb
<div class="row product_item">
  <div class="col image">
    <% if product.picture.exists? %>
      <img src="<%= product.picture.url(:thumb) %>"/>
    <% end %>
  </div>
  <div class="col details">
    <%= link_to product.title, product_path(product), class: 'header_link' %>
    <p>
      <%= product.description %>
    </p>
    <span><%= product.subscriber_count %> subscribers</span>
    <% if user_signed_in? %>
      <% if product.subscribers.where(id: current_user.id).empty? %>
        <span><%= link_to '(subscribe)', subscribe_product_path(product), method: :put %></span>
      <% else %>
        <span><%= link_to '(unsubscribe)', unsubscribe_product_path(product), method: :delete %></span>
      <% end %>
    <% end %>
    <span>
    <span><%= link_to "Visit site", product.website_url, class: 'link', target: '_blank', rel: 'nofollow' %></span>
    <br />
    <span>Tags: <%= product.tag_list %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= link_to 'New Product', new_product_path %>
<br />
<br />
<% @products.each do |product| %>
  <%= render 'item', product: product %>
  <%= link_to 'Show', product %>
  <%= link_to 'Edit', edit_product_path(product) %>
  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= render 'item', product: @product %>
<%= link_to 'Back', url_for(:back) %>

app/views/shared/_nav.html.erb
<div id="nav">
  <div class="container">
    <div class="menu">
      <ul>
        <li><%= render 'shared/search' %></li>
        <li><%= link_to "All Products", root_path() %></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Subscriptions", mine_home_index_path() %></li>
        <% end %>
      </ul>
    </div>
    <div class="user_info">
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'button' %></li>
        <% else %>
          <li><%= link_to "Log in", new_session_path(:user), class: 'button' %></li>
          <li><%= link_to "Sign up", new_registration_path(:user), class: 'button colored' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= form_tag '', method: :get, enforce_utf8: false do %>
  <%= text_field_tag 'search', params[:search], placeholder: 'Search for product...' %>
  <%= submit_tag 'Search', class: 'button colored', name: nil %>
<% end %>

app/views/tags/_index.html.erb
<ul>
  <li><%= link_to 'all' %></li>
  <% tags.each do |tag| %>
    <%= render 'tags/item', tag: tag %>
<% end %>
</ul>

app/views/tags/_item.html.erb
<li>
  <%= link_to tag.description, params.permit(:tag).merge(tag: tag.description, search: params[:search]) %>
</li>